language: python
python:
- '3.5'
services:
- redis-server
install:
- pip install -r requirements.txt
script:
- python manage.py test --settings=kmcoffice.settings_test
deploy:
  provider: heroku
  api_key:
    secure: DVkjdrbr1auv4V9yr9XoLScwQl3sRSR+gqY7AhdMhBhMf+TI/4u47VQ5qlcBcJRhoSEwZMqHazmzND/njp4T+KekM8dIEdmqFYFnKoDF606sHgrmlzNRE7DBS9wNal0Fq628FyfOZGo4FfXmeWZO3RM6RxGOhUAIqAy3EZOii46hnoxSjpT3yTsEqlXP07u0wvg8V8acqH4mmsCji7rCygKlYfngkDy7ZLy+Ch8MJFdtoVArL5+kqCxhu4dTqQEx3K6qHOyE3yq1MEteyMS5i/laeH6VcdWcPGxFI/ma33P2ZASAJ0sDgqJ0Zz1AXW4AsKhacc7tQiPLvzLedYzEO8ZO75GVjRG/J103HQmrnMt9G8rfk90WwgzfR5iYPg6UOz4+ImjEVgC4o6Gr2HNSxiwywdrgenfQLXdf03FdJ73ggRjLeOBpsal+rNuDuixrSG7xSz4qh4KVeBMYFvYSoen5s6TJW+xcIfKD8ZcN/EFvClxA2JXWf64QxO0XEdMgjtWyJWcYjhGVfZWa5VDkjGZYgeiR7+toJpqGzgaM4s18yhEcgiJ3Ub+QHcFQSfFgQ1Iw9UHndz5vmg84rMS2gzHh4gKLbRsIXwAfNoqj8v8nA86uCnBZoxnrelf/IWPJljyWyRyIxwjKkzIIpctYEpovoE5a2zn6Jhx4YJEF5Cw=
