language: python
python:
- '3.5'
services:
- redis-server
install:
- pip install -r requirements.txt
script:
- python manage.py test --settings=kmcoffice.settings_test
deploy:
  provider: heroku
  api_key:
    secure: vwtdi1hS0M9dgmknXv4FrCC8Fvubl3CtuD4Z2Vp7c76I4KkRFHCpoemOHu6LAkaWbiDTdSsQtVXqFw94T19Sx3B7rgNy05cgTHEGqIpU/8uVK73S5QqF7jiLSd/zBbSUEUSq5Trmmb+xibJk5qUpzU9Ua4sOuHsMlUzORwWTqRwfgskDskHcSc/trXwmLoime3RWL7UGT2nAzTpVLBjNnWNo6wfUMPLxSk/E2+zhllkZV6dBqYXXjGjUqRupxOfevsY7e2RGFMe9M4icYwOCD7rT/KShctgJJiqlLIfuRUjdyECQcc/ifHz8F1+xjYsOgzmC4sOK3QUb1fKY5X4q2QdyU+UVP5KemAGXe9aufZIIekHzzGJNQ6nWQ7iYyHBmGwXR+nmErzc0ZCxuoevP4Ud+rb8JFldDx3aD0+egYNQfXNSYQwUbcxnsK5LuWxnd/gCwCLzY/GePXNQgAWMJbsgTmGUVvS8zIGAgruMxJlaAkOiAMKpzgg79+1TdWQ0VT0nKoirpe4zi/FrOwDmgJnvNBnVr8lrmj5mtr53c5ynyg7WJqqhFh2mwqoELme0S3YGxfS/tef8A12KhWI8OXDmOCVqvHSgyL5IGzuiduWempHlnu6Sx+OJbx7/a/l7UEYOBYIW9QnD+zJHYzrClpKnp8/cVCars5ejjlXqf6ek=
  app: kmcoffice
  on:
    repo: tornadoalert/kmcoffice
