language: python
python:
- '3.5'
services:
- redis-server
install:
- pip install -r requirements.txt
script:
- python manage.py test --settings=kmcoffice.settings_test
deploy:
  provider: heroku
  api_key:
    secure: "oW/r1Nea3VrhPjp09RitTnRKIKMDbiors218TJwP7Pb99F2bYtTsCk00qdvBy5lriE9AMd0M7snadqojgiiBcqG/lzV9GIZn1CElB/gPwIP+lazZEoA0urzcpvJT2yLImamWHVajwJNHoFMZ
PqX3LwJvdZwfWcg7xhGs11by2Su23l5PaXThyVbIT+yEoItir+dC+j6JqySKvQSxSnH9UpcO0g2NgGLbHUpURGJvUAjVLwYihPaZPEVspuYsbnENBf4lq/ZF+nOLelvWIpF0SfEtiX+JayhK5DdHM5gb5XH
lyqnCxFK+lAaGxz8Cn80Jf4OnReZDzy03sdvfMhP6ct8h0/AYxtIZjyizbOI1OcOI/u8beDLVkxIXjRhqBZYPeqv2tvaHT1NBc74jCgS3CXb9v1pdrnZITgaag2OC62ZvdUs6VoR2ezDmTQIfp8gM4GomRV
UjilFpZmREIP7qUPYsc92pklXjLdLqM76WVN8JpkJzSef0VdXVzSD7KzD0xatiWadqa3pP+vgeNxerTsoNXNnvvufMF3KFaGa2LmohGOnpJCBzQ0fyEa7Xil0EuA/XW2b/QWvdyW3R79kDSLePt0XNByrXg
MZixgbEqyW8HYHLis0lLXJThQfRsVt2KIiKWfvRU4hkkOPZhx5hwMeI1Hm4GDbbA21SPaUaGg0="
  app: kmcoffice
  on:
    repo: tornadoalert/kmcoffice
