language: python
python:
- '3.5'
services:
- redis-server
install:
- pip install -r requirements.txt
script:
- python manage.py test --settings=kmcoffice.settings_test
deploy:
  provider: heroku
  api_key:
    secure: D7v4pVkl/XVbKXyGm9I8RsC/x8Djn9dJ9DzedZI+7yw+PWbgO3E8U1XEU16Vm4kOnRBspagWRQt50w7dP8zAs1X47h3VBJOBcKJX/NzJK9HdV7uOOYqC3FekahQEyH8wa5ayempp7XhKKK2KmAR7RpqJTmBU+4giLwUCGe0nE681WfaSwYcy3+smyWYVO4e4O8yWNHN6syrseVGNbWwrGjbcp1C/D3I6EC2EPDVC/Ptuo1/ZvIYJtbA9eRuNpF5Iyg0KHwvaLy/v3QSRXIC8xbnh6ERsk8xdTaTMqRp79ensn4LU7j5gRzreL7Ffj5d0R/nbpqgncbRnLgxD9KKEDjBkQ8oIt2UAqPXG9GLTyICtcJqOKyOXHmgz8v+tZV/eAsIv/qpC2OABadmfuFJv5nslgDy9TAYOQGzqxdxIMH96gNQrMBWDmSQa5VUK8AbOKV3NK8426q3ThK8uAk1eZ3ESa2NZ/5k5HUlCHpKAWJ0nVJXu8ndWhhiEzdrEJ9ENamRJcpMFRCJMj0LX07+r3pi+DAW66nKqVUsXthWpekilGoym2fhKR8Otp7iv9g4bPwdkJjwUeScMzD8UkJMBn4B0HfOk3qtsxILDa1AYQnNIk0Jba53p4di1mYtOrhEuP2f5n4J6FpWCI3f2G92so5lO/kbC9gope89DE2CFa24=
  app: kmcmanipal
  on:
    repo: tornadoalert/kmcoffice
