language: python
python:
- '3.5'
services:
- redis-server
install:
- pip install -r requirements.txt
script:
- python manage.py test --settings=kmcoffice.settings_test
deploy:
  provider: heroku
  api_key:
    secure: CS2H6cz5yWVm26qg+siKZlJO/ecMWLvl5FDo/REZ7adId7+YYtZkseM8PZDvQEdg7dltHmMnd/ekRySOMg27HEEVI28jL8xofyHcgleuIH2+b4mIetkbbD9fSDQhRj7zDRtLdmrRkLny/Vtbua7wKCMTiMTF6U3Xwil6H/pYVcnYyeSpALhHgzKVTaA6UyCGaDqvdSebQkRL4EqlIyfVTI5QngRqzH7Vcg5Ywaw1dJim06MuQLVBtaxXW1fKeGyynYB7T/bcYKf5TDac+8NqKd62l5wn2+TNhQCd06nXljMt6ngByLfIbCSFJ1mZtOxzBMUcWV8Ffo0hdBXxkVU0nyD/AWAHm6revvYWTxPm1NradVcRKWe/7q5ElPGFW/xYe8ZecUvOUiKJUckZv9/CmZ9U0e6IOM5llIKgyn0xsfFEp27R+kAoqy5WCjX5V61a1v2yyh1AcFGctetuf22kP8BQjtnW1Ll4/hwrEUY8eJHY8gzys9aJkujn6EQPjGzwCniGq/NTS0UAdR8jLABMGWjRAtowLYSgSMtFEmZIDCENSZJocdj18+v0SHq0Yiegec3+/IGcQZPlICD58+VVohLteb1oavBiCiH5SeWVff26Af0ChGjET/lz1BKfLx8Bn+8U9efj43q+WK4i256R5+rv9dbu1OP+EWXjxlRWb88=
  app: kmcoffice
  on:
    repo: tornadoalert/kmcoffice
