language: python
python:
- '3.5'
services:
- redis-server
install:
- pip install -r requirements.txt
script:
- python manage.py test --settings=kmcoffice.settings_test
deploy:
  provider: heroku
  api_key:
    secure: tsTvaa6XKpFPWw8xo/w2KQDy0uRMbKNpwcp3batpFLipD11Z7Ae3vHZz24CObPZtAyICrLGQC8vtfKgXv73L3qKQ/jwM0itk2hgpXl83r3V2TcaaFJbjRe1XVr1vbt6c06z2pyXFGnnuET95Agq3iqOOE8y44YQ/OYuLLAYrxiT4U8zQCk/2urumCTDzstM9srltWW0iov1gzkAaZeTZM4McdFiSflJK4OlMo3mZiu/K7PzEHJdfH1ENbv1matAOCQVHcrj+9MnJfXBy149tOT6PeJnByyGIz5y4hLXiwTjzYQMNPJHX/hX/+/AHF531vHmMta+gEK2ntwsVPRyehC9lAGMCht6rMya3Ev7wWHIQ9iav3Go1pXc2dozuWK1IZcBFe6uFoArvEzR3ZLWgJl08r+gNq4jsv1vQtCAb02HVBIwSxOAryk2g+hNjmC5445nZIMemaTkIe37FYJm0SsfhNmWzoFjVVvnbsYuxWzDpGeoJ9NfMcfchvecS45SEV9RC61gX4TxhUbmLB59OVwFfdLkyY04fUB/souRroRGeAdPoBkERmQWCW5CXqr51M+NlUh2rL3OmLwMUqR9YeCNHmbbWtUqqlp3FlI4yt9UxrZSQ1mkEwWj+1X4gIItB8PCoYA7vdxim4F1wXrLYNplpuUpGRlyMOIwmIm7FoMI=
