language: python
python:
  - "3.5"
before_install:
  - export DJANGO_SETTINGS_MODULE=kmcoffice.settings
  - export python_files = tests.py test_*.py *_tests.py
install: 
  - "pip install -r requirements.txt"
script: pytest
