# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='approved',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('1', 'Awaiting'), ('2', 'No'), ('3', 'Yes')], default='1', max_length=1),
        ),
    ]
