# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_auto_20170819_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('2', 'No'), ('3', 'Yes')], default='1', max_length=1),
        ),
    ]
