# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0003_auto_20170819_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='notification_email',
            field=models.EmailField(default='tornadoalert@gmail.com', max_length=254),
        ),
    ]
