# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0004_booking_notification_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='notification_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
