# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0005_auto_20170916_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCalander',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Event', max_length=200)),
                ('calander_id', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
