# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20170901_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='pre_claim_approved',
        ),
    ]
