# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20170903_0038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'permissions': (('claim_js_approve', 'Can approve the claim with js status'), ('claim_sis_approve', 'Can approve the claim with sis status'))},
        ),
    ]
