# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_auto_20170903_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='preclaim',
            name='notification_email',
            field=models.EmailField(default='tornadoalert@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
