# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_preclaim_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='preclaim',
            name='faculty_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
